#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026 retrodiv <retrodiv@proton.me>
# Validate every ref being sent, including tags and non-checked-out branches.
set -eu
root=$(git rev-parse --show-toplevel)
while read -r local_ref local_oid remote_ref remote_oid; do
    case "$local_oid" in
        *[!0]*) "${PYTHON:-python3}" "$root/tools/check_revision.py" "$local_oid" ;;
    esac
done
